# Generated by Django 2.2.3 on 2019-07-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('class_sd', models.FloatField()),
                ('class_average', models.FloatField()),
                ('class_total', models.IntegerField()),
                ('expected_grade', models.CharField(max_length=3)),
                ('mid_ratio', models.FloatField()),
                ('final_ratio', models.FloatField()),
            ],
        ),
    ]
