# Generated by Django 2.2.3 on 2019-07-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='lecture',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='my_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='professor',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
