# Generated by Django 2.2.3 on 2019-07-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0003_score_lecture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='first_grade',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='first_percentage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='final_ratio',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='score',
            name='mid_ratio',
            field=models.FloatField(default=50),
        ),
    ]
