# Generated by Django 2.2.4 on 2019-08-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0004_auto_20190730_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='lecture',
            new_name='lecture_professor',
        ),
        migrations.RemoveField(
            model_name='score',
            name='class_average',
        ),
        migrations.RemoveField(
            model_name='score',
            name='class_sd',
        ),
        migrations.RemoveField(
            model_name='score',
            name='my_score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='professor',
        ),
        migrations.AddField(
            model_name='score',
            name='a_ratio',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='b_ratio',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='final_grade',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='final_percentage',
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='happythinking',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='professor_style',
            field=models.CharField(default='비율 채워줌', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='rivals_to_win',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='user_content',
            field=models.CharField(default='난 원래 기말에 모든 걸 걸었지', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='lecture_type',
            field=models.CharField(max_length=5),
        ),
    ]
