# Generated by Django 2.2.4 on 2019-08-09 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0005_auto_20190809_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_percentage', models.FloatField()),
                ('a_ratio2', models.IntegerField()),
                ('b_ratio2', models.IntegerField()),
                ('happythinking', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='final_grade',
        ),
        migrations.RemoveField(
            model_name='score',
            name='final_percentage',
        ),
        migrations.RemoveField(
            model_name='score',
            name='happythinking',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rivals_to_win',
        ),
        migrations.RemoveField(
            model_name='score',
            name='user_content',
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.CharField(max_length=5)),
                ('rivals_to_win', models.IntegerField()),
                ('user_content', models.CharField(default=' ', max_length=100)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.Score')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.Happy')),
            ],
        ),
        migrations.AddField(
            model_name='happy',
            name='first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreapp.Score'),
        ),
    ]
