# Generated by Django 2.2.4 on 2019-08-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0006_auto_20190809_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='final_grade',
        ),
        migrations.AddField(
            model_name='submit',
            name='final_percentage',
            field=models.IntegerField(default=5),
        ),
    ]
