# Generated by Django 3.0.8 on 2020-07-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreapp', '0009_auto_20200709_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submit',
            old_name='first_input',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='submit',
            name='final_percentage',
        ),
    ]
